services:
  music-app:
    build: .
    restart: unless-stopped
    privileged: true
    devices:
      - /dev/fb0:/dev/fb0
      - /dev/tty1:/dev/tty1
      - /dev/snd:/dev/snd
    volumes:
      - /dev/input:/dev/input
      - /home/gregtis/music_library:/library:ro
    environment:
      - SDL_VIDEODRIVER=offscreen
      - SDL_AUDIODRIVER=alsa
      - PYTHONUNBUFFERED=1
      - LIBRARY_DIR=/library
