services:
  music-app:
    build: .
    restart: unless-stopped
    privileged: true
    devices:
      - /dev/dri/card0:/dev/dri/card0
      - /dev/dri/renderD128:/dev/dri/renderD128
      - /dev/snd:/dev/snd
    volumes:
      - /dev/input:/dev/input
    environment:
      - SDL_VIDEODRIVER=kmsdrm
      - SDL_AUDIODRIVER=alsa
